steps:
- name: 'docker/compose:1.21.1'
  args: ['up','-d']
- name: 'eu.gcr.io/cloud-builders/docker'
  args: ['tag', 'docker-nginx-php-mongo:latest', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['eu.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
