steps:
- name: 'docker/compose:1.21.1'
  args: ['up','-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['ps']
- name: 'gcr.io/cloud-builders/docker'
#  args: ['tag', 'nginx:latest', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME_nginx:$COMMIT_SHA']
  args: ['tag', 'nginx:latest', 'eu.gcr.io/$PROJECT_ID/nginx:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'nanoninja/php-fpm', 'eu.gcr.io/$PROJECT_ID/nanoninja_php:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'mongo', 'eu.gcr.io/$PROJECT_ID/mongo:$COMMIT_SHA']
images: ['eu.gcr.io/$PROJECT_ID/nginx:$COMMIT_SHA','eu.gcr.io/$PROJECT_ID/nanoninja_php:$COMMIT_SHA','eu.gcr.io/$PROJECT_ID/mongo:$COMMIT_SHA']
