steps:
- name: 'docker/compose:1.21.1'
  args: ['up','-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['ps','-a']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'nanoninja/php-fpm', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['eu.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
